spring.datasource.url=jdbc:postgresql://localhost:5432/gamelibrary
spring.datasource.username=postgres
spring.datasource.password=erzat.myr

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.sql.init.mode=always
